create table if not exists public.computer_stock (
  id bigint generated by default as identity primary key,
  particulars text not null,
  quantity_mtrs numeric not null check (quantity_mtrs >= 0),
  created_at timestamp with time zone not null default now()
);
